/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Organization metrics and statistics
 * @export
 * @interface OrganisationsOrgIdStatusGet200ResponseMetrics
 */
export interface OrganisationsOrgIdStatusGet200ResponseMetrics {
    /**
     * Total number of feedback items
     * @type {number}
     * @memberof OrganisationsOrgIdStatusGet200ResponseMetrics
     */
    feedbackCount: number;
    /**
     * Total number of opportunities
     * @type {number}
     * @memberof OrganisationsOrgIdStatusGet200ResponseMetrics
     */
    opportunityCount: number;
    /**
     * Total number of solutions
     * @type {number}
     * @memberof OrganisationsOrgIdStatusGet200ResponseMetrics
     */
    solutionCount: number;
    /**
     * Total number of outcomes
     * @type {number}
     * @memberof OrganisationsOrgIdStatusGet200ResponseMetrics
     */
    outcomeCount: number;
}

/**
 * Check if a given object implements the OrganisationsOrgIdStatusGet200ResponseMetrics interface.
 */
export function instanceOfOrganisationsOrgIdStatusGet200ResponseMetrics(value: object): value is OrganisationsOrgIdStatusGet200ResponseMetrics {
    if (!('feedbackCount' in value) || value['feedbackCount'] === undefined) return false;
    if (!('opportunityCount' in value) || value['opportunityCount'] === undefined) return false;
    if (!('solutionCount' in value) || value['solutionCount'] === undefined) return false;
    if (!('outcomeCount' in value) || value['outcomeCount'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdStatusGet200ResponseMetricsFromJSON(json: any): OrganisationsOrgIdStatusGet200ResponseMetrics {
    return OrganisationsOrgIdStatusGet200ResponseMetricsFromJSONTyped(json, false);
}

export function OrganisationsOrgIdStatusGet200ResponseMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdStatusGet200ResponseMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'feedbackCount': json['feedbackCount'],
        'opportunityCount': json['opportunityCount'],
        'solutionCount': json['solutionCount'],
        'outcomeCount': json['outcomeCount'],
    };
}

export function OrganisationsOrgIdStatusGet200ResponseMetricsToJSON(json: any): OrganisationsOrgIdStatusGet200ResponseMetrics {
    return OrganisationsOrgIdStatusGet200ResponseMetricsToJSONTyped(json, false);
}

export function OrganisationsOrgIdStatusGet200ResponseMetricsToJSONTyped(value?: OrganisationsOrgIdStatusGet200ResponseMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feedbackCount': value['feedbackCount'],
        'opportunityCount': value['opportunityCount'],
        'solutionCount': value['solutionCount'],
        'outcomeCount': value['outcomeCount'],
    };
}

