/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SolutionRefinementLogInner } from './SolutionRefinementLogInner.js';
import {
    SolutionRefinementLogInnerFromJSON,
    SolutionRefinementLogInnerFromJSONTyped,
    SolutionRefinementLogInnerToJSON,
    SolutionRefinementLogInnerToJSONTyped,
} from './SolutionRefinementLogInner.js';

/**
 * Request schema for creating a requirement
 * @export
 * @interface CreateRequirement
 */
export interface CreateRequirement {
    /**
     * 
     * @type {string}
     * @memberof CreateRequirement
     */
    id?: string;
    /**
     * System prompt used to generate the requirement
     * @type {string}
     * @memberof CreateRequirement
     */
    systemPrompt?: string | null;
    /**
     * Current state of AI processing
     * @type {string}
     * @memberof CreateRequirement
     */
    aiProcessingState: CreateRequirementAiProcessingStateEnum;
    /**
     * Log of refinements made to the requirement
     * @type {Array<SolutionRefinementLogInner>}
     * @memberof CreateRequirement
     */
    refinementLog: Array<SolutionRefinementLogInner>;
    /**
     * Title of the requirement
     * @type {string}
     * @memberof CreateRequirement
     */
    title: string;
    /**
     * Description of the requirement
     * @type {string}
     * @memberof CreateRequirement
     */
    description: string;
    /**
     * The feature this requirement belongs to
     * @type {string}
     * @memberof CreateRequirement
     */
    feature: string;
    /**
     * Detailed requirements specification
     * @type {string}
     * @memberof CreateRequirement
     */
    requirements: string;
    /**
     * ID of the requirement owner
     * @type {string}
     * @memberof CreateRequirement
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRequirement
     */
    status: CreateRequirementStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateRequirement
     */
    solutionIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateRequirement
     */
    opportunityIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateRequirement
     */
    feedbackIds?: Array<string>;
}


/**
 * @export
 */
export const CreateRequirementAiProcessingStateEnum = {
    Initial: 'INITIAL',
    Processing: 'PROCESSING',
    Finished: 'FINISHED',
    Error: 'ERROR'
} as const;
export type CreateRequirementAiProcessingStateEnum = typeof CreateRequirementAiProcessingStateEnum[keyof typeof CreateRequirementAiProcessingStateEnum];

/**
 * @export
 */
export const CreateRequirementStatusEnum = {
    Draft: 'draft',
    Ready: 'ready',
    Complete: 'complete'
} as const;
export type CreateRequirementStatusEnum = typeof CreateRequirementStatusEnum[keyof typeof CreateRequirementStatusEnum];


/**
 * Check if a given object implements the CreateRequirement interface.
 */
export function instanceOfCreateRequirement(value: object): value is CreateRequirement {
    if (!('aiProcessingState' in value) || value['aiProcessingState'] === undefined) return false;
    if (!('refinementLog' in value) || value['refinementLog'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('feature' in value) || value['feature'] === undefined) return false;
    if (!('requirements' in value) || value['requirements'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateRequirementFromJSON(json: any): CreateRequirement {
    return CreateRequirementFromJSONTyped(json, false);
}

export function CreateRequirementFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRequirement {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'systemPrompt': json['systemPrompt'] == null ? undefined : json['systemPrompt'],
        'aiProcessingState': json['aiProcessingState'],
        'refinementLog': ((json['refinementLog'] as Array<any>).map(SolutionRefinementLogInnerFromJSON)),
        'title': json['title'],
        'description': json['description'],
        'feature': json['feature'],
        'requirements': json['requirements'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'status': json['status'],
        'solutionIds': json['solutionIds'] == null ? undefined : json['solutionIds'],
        'opportunityIds': json['opportunityIds'] == null ? undefined : json['opportunityIds'],
        'feedbackIds': json['feedbackIds'] == null ? undefined : json['feedbackIds'],
    };
}

export function CreateRequirementToJSON(json: any): CreateRequirement {
    return CreateRequirementToJSONTyped(json, false);
}

export function CreateRequirementToJSONTyped(value?: CreateRequirement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'systemPrompt': value['systemPrompt'],
        'aiProcessingState': value['aiProcessingState'],
        'refinementLog': ((value['refinementLog'] as Array<any>).map(SolutionRefinementLogInnerToJSON)),
        'title': value['title'],
        'description': value['description'],
        'feature': value['feature'],
        'requirements': value['requirements'],
        'ownerId': value['ownerId'],
        'status': value['status'],
        'solutionIds': value['solutionIds'],
        'opportunityIds': value['opportunityIds'],
        'feedbackIds': value['feedbackIds'],
    };
}

