/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ListOutcomes500ResponseError
 */
export interface ListOutcomes500ResponseError {
  [key: string]: any | any;
  /**
   * Error code identifier
   * @type {string}
   * @memberof ListOutcomes500ResponseError
   */
  code: string;
  /**
   * Human-readable error description
   * @type {string}
   * @memberof ListOutcomes500ResponseError
   */
  description: string;
}

/**
 * Check if a given object implements the ListOutcomes500ResponseError interface.
 */
export function instanceOfListOutcomes500ResponseError(
  value: object,
): value is ListOutcomes500ResponseError {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  return true;
}

export function ListOutcomes500ResponseErrorFromJSON(
  json: any,
): ListOutcomes500ResponseError {
  return ListOutcomes500ResponseErrorFromJSONTyped(json, false);
}

export function ListOutcomes500ResponseErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListOutcomes500ResponseError {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    code: json["code"],
    description: json["description"],
  };
}

export function ListOutcomes500ResponseErrorToJSON(
  json: any,
): ListOutcomes500ResponseError {
  return ListOutcomes500ResponseErrorToJSONTyped(json, false);
}

export function ListOutcomes500ResponseErrorToJSONTyped(
  value?: ListOutcomes500ResponseError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    code: value["code"],
    description: value["description"],
  };
}
