/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: help@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Outcome } from "./Outcome.js";
import { OutcomeFromJSON, OutcomeToJSON } from "./Outcome.js";

/**
 * Response containing an array of outcomes
 * @export
 * @interface ListOutcomes200Response
 */
export interface ListOutcomes200Response {
  [key: string]: any | any;
  /**
   * Array of outcomes
   * @type {Array<Outcome>}
   * @memberof ListOutcomes200Response
   */
  data: Array<Outcome>;
}

/**
 * Check if a given object implements the ListOutcomes200Response interface.
 */
export function instanceOfListOutcomes200Response(
  value: object,
): value is ListOutcomes200Response {
  if (!("data" in value) || value["data"] === undefined) return false;
  return true;
}

export function ListOutcomes200ResponseFromJSON(
  json: any,
): ListOutcomes200Response {
  return ListOutcomes200ResponseFromJSONTyped(json, false);
}

export function ListOutcomes200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListOutcomes200Response {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    data: (json["data"] as Array<any>).map(OutcomeFromJSON),
  };
}

export function ListOutcomes200ResponseToJSON(
  json: any,
): ListOutcomes200Response {
  return ListOutcomes200ResponseToJSONTyped(json, false);
}

export function ListOutcomes200ResponseToJSONTyped(
  value?: ListOutcomes200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    data: (value["data"] as Array<any>).map(OutcomeToJSON),
  };
}
