/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request body for managing outcome relationships
 * @export
 * @interface ManageOutcomeRelationshipsRequest
 */
export interface ManageOutcomeRelationshipsRequest {
    /**
     * Array of opportunity IDs to associate with the outcome
     * @type {Array<string>}
     * @memberof ManageOutcomeRelationshipsRequest
     */
    opportunityIds?: Array<string>;
    /**
     * Array of solution IDs to associate with the outcome
     * @type {Array<string>}
     * @memberof ManageOutcomeRelationshipsRequest
     */
    solutionIds?: Array<string>;
    /**
     * Array of feedback IDs to associate with the outcome
     * @type {Array<string>}
     * @memberof ManageOutcomeRelationshipsRequest
     */
    feedbackIds?: Array<string>;
}

/**
 * Check if a given object implements the ManageOutcomeRelationshipsRequest interface.
 */
export function instanceOfManageOutcomeRelationshipsRequest(value: object): value is ManageOutcomeRelationshipsRequest {
    return true;
}

export function ManageOutcomeRelationshipsRequestFromJSON(json: any): ManageOutcomeRelationshipsRequest {
    return ManageOutcomeRelationshipsRequestFromJSONTyped(json, false);
}

export function ManageOutcomeRelationshipsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManageOutcomeRelationshipsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'opportunityIds': json['opportunityIds'] == null ? undefined : json['opportunityIds'],
        'solutionIds': json['solutionIds'] == null ? undefined : json['solutionIds'],
        'feedbackIds': json['feedbackIds'] == null ? undefined : json['feedbackIds'],
    };
}

export function ManageOutcomeRelationshipsRequestToJSON(json: any): ManageOutcomeRelationshipsRequest {
    return ManageOutcomeRelationshipsRequestToJSONTyped(json, false);
}

export function ManageOutcomeRelationshipsRequestToJSONTyped(value?: ManageOutcomeRelationshipsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opportunityIds': value['opportunityIds'],
        'solutionIds': value['solutionIds'],
        'feedbackIds': value['feedbackIds'],
    };
}

