/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for updating onboarding
 * @export
 * @interface OnboardingUpdatePayload
 */
export interface OnboardingUpdatePayload {
    /**
     * Name of the organization to create
     * @type {string}
     * @memberof OnboardingUpdatePayload
     */
    name: string;
    /**
     * Description of the organization for generating workspace and outcomes
     * @type {string}
     * @memberof OnboardingUpdatePayload
     */
    description: string;
}

/**
 * Check if a given object implements the OnboardingUpdatePayload interface.
 */
export function instanceOfOnboardingUpdatePayload(value: object): value is OnboardingUpdatePayload {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function OnboardingUpdatePayloadFromJSON(json: any): OnboardingUpdatePayload {
    return OnboardingUpdatePayloadFromJSONTyped(json, false);
}

export function OnboardingUpdatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingUpdatePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function OnboardingUpdatePayloadToJSON(json: any): OnboardingUpdatePayload {
    return OnboardingUpdatePayloadToJSONTyped(json, false);
}

export function OnboardingUpdatePayloadToJSONTyped(value?: OnboardingUpdatePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

