/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OnboardingResponseData } from "./OnboardingResponseData.js";
import {
  OnboardingResponseDataFromJSON,
  OnboardingResponseDataToJSON,
} from "./OnboardingResponseData.js";

/**
 * Response schema for onboarding
 * @export
 * @interface OnboardingResponse
 */
export interface OnboardingResponse {
  /**
   *
   * @type {OnboardingResponseData}
   * @memberof OnboardingResponse
   */
  data: OnboardingResponseData;
}

/**
 * Check if a given object implements the OnboardingResponse interface.
 */
export function instanceOfOnboardingResponse(
  value: object,
): value is OnboardingResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  return true;
}

export function OnboardingResponseFromJSON(json: any): OnboardingResponse {
  return OnboardingResponseFromJSONTyped(json, false);
}

export function OnboardingResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OnboardingResponse {
  if (json == null) {
    return json;
  }
  return {
    data: OnboardingResponseDataFromJSON(json["data"]),
  };
}

export function OnboardingResponseToJSON(json: any): OnboardingResponse {
  return OnboardingResponseToJSONTyped(json, false);
}

export function OnboardingResponseToJSONTyped(
  value?: OnboardingResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: OnboardingResponseDataToJSON(value["data"]),
  };
}
