/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OnboardPost200ResponseOutcomesInner } from './OnboardPost200ResponseOutcomesInner.js';
import {
    OnboardPost200ResponseOutcomesInnerFromJSON,
    OnboardPost200ResponseOutcomesInnerFromJSONTyped,
    OnboardPost200ResponseOutcomesInnerToJSON,
    OnboardPost200ResponseOutcomesInnerToJSONTyped,
} from './OnboardPost200ResponseOutcomesInner.js';
import type { OnboardPost200ResponseWorkspace } from './OnboardPost200ResponseWorkspace.js';
import {
    OnboardPost200ResponseWorkspaceFromJSON,
    OnboardPost200ResponseWorkspaceFromJSONTyped,
    OnboardPost200ResponseWorkspaceToJSON,
    OnboardPost200ResponseWorkspaceToJSONTyped,
} from './OnboardPost200ResponseWorkspace.js';
import type { OnboardPost200ResponseOrganisation } from './OnboardPost200ResponseOrganisation.js';
import {
    OnboardPost200ResponseOrganisationFromJSON,
    OnboardPost200ResponseOrganisationFromJSONTyped,
    OnboardPost200ResponseOrganisationToJSON,
    OnboardPost200ResponseOrganisationToJSONTyped,
} from './OnboardPost200ResponseOrganisation.js';

/**
 * 
 * @export
 * @interface OnboardPost200Response
 */
export interface OnboardPost200Response {
    /**
     * 
     * @type {OnboardPost200ResponseWorkspace}
     * @memberof OnboardPost200Response
     */
    workspace: OnboardPost200ResponseWorkspace;
    /**
     * 
     * @type {Array<OnboardPost200ResponseOutcomesInner>}
     * @memberof OnboardPost200Response
     */
    outcomes: Array<OnboardPost200ResponseOutcomesInner>;
    /**
     * 
     * @type {OnboardPost200ResponseOrganisation}
     * @memberof OnboardPost200Response
     */
    organisation: OnboardPost200ResponseOrganisation;
}

/**
 * Check if a given object implements the OnboardPost200Response interface.
 */
export function instanceOfOnboardPost200Response(value: object): value is OnboardPost200Response {
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    if (!('outcomes' in value) || value['outcomes'] === undefined) return false;
    if (!('organisation' in value) || value['organisation'] === undefined) return false;
    return true;
}

export function OnboardPost200ResponseFromJSON(json: any): OnboardPost200Response {
    return OnboardPost200ResponseFromJSONTyped(json, false);
}

export function OnboardPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'workspace': OnboardPost200ResponseWorkspaceFromJSON(json['workspace']),
        'outcomes': ((json['outcomes'] as Array<any>).map(OnboardPost200ResponseOutcomesInnerFromJSON)),
        'organisation': OnboardPost200ResponseOrganisationFromJSON(json['organisation']),
    };
}

export function OnboardPost200ResponseToJSON(json: any): OnboardPost200Response {
    return OnboardPost200ResponseToJSONTyped(json, false);
}

export function OnboardPost200ResponseToJSONTyped(value?: OnboardPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workspace': OnboardPost200ResponseWorkspaceToJSON(value['workspace']),
        'outcomes': ((value['outcomes'] as Array<any>).map(OnboardPost200ResponseOutcomesInnerToJSON)),
        'organisation': OnboardPost200ResponseOrganisationToJSON(value['organisation']),
    };
}

