/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OnboardPost200ResponseOrganisation
 */
export interface OnboardPost200ResponseOrganisation {
    /**
     * Unique identifier for the organization
     * @type {string}
     * @memberof OnboardPost200ResponseOrganisation
     */
    id: string;
    /**
     * Name of the organization
     * @type {string}
     * @memberof OnboardPost200ResponseOrganisation
     */
    name: string;
}

/**
 * Check if a given object implements the OnboardPost200ResponseOrganisation interface.
 */
export function instanceOfOnboardPost200ResponseOrganisation(value: object): value is OnboardPost200ResponseOrganisation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OnboardPost200ResponseOrganisationFromJSON(json: any): OnboardPost200ResponseOrganisation {
    return OnboardPost200ResponseOrganisationFromJSONTyped(json, false);
}

export function OnboardPost200ResponseOrganisationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardPost200ResponseOrganisation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function OnboardPost200ResponseOrganisationToJSON(json: any): OnboardPost200ResponseOrganisation {
    return OnboardPost200ResponseOrganisationToJSONTyped(json, false);
}

export function OnboardPost200ResponseOrganisationToJSONTyped(value?: OnboardPost200ResponseOrganisation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

