/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganisationsGet200ResponseDataInner
 */
export interface OrganisationsGet200ResponseDataInner {
    /**
     * Number of unprocessed feedback items
     * @type {number}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    unprocessedFeedbackCount: number;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    id: string;
    /**
     * Name of the organisation
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    name: string;
    /**
     * Stripe customer ID for billing
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    stripeCustomerId?: string;
    /**
     * URL to the organisation's homepage
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    homepageUrl?: string | null;
    /**
     * URL to the organisation's logo
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    logoUrl?: string | null;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    createdAt: string;
    /**
     * Account type
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    accountType: OrganisationsGet200ResponseDataInnerAccountTypeEnum;
    /**
     * The start date of the current billing cycle.
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    billingCycleStartDate: string;
    /**
     * Number of flex credits available at the start of the current billing cycle.
     * @type {number}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    billingCycleFlexCreditAllowance: number;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    updatedAt: string;
    /**
     * Status of the organisation
     * @type {string}
     * @memberof OrganisationsGet200ResponseDataInner
     */
    status: OrganisationsGet200ResponseDataInnerStatusEnum;
}


/**
 * @export
 */
export const OrganisationsGet200ResponseDataInnerAccountTypeEnum = {
    Hobby: 'HOBBY',
    Professional: 'PROFESSIONAL',
    Team: 'TEAM'
} as const;
export type OrganisationsGet200ResponseDataInnerAccountTypeEnum = typeof OrganisationsGet200ResponseDataInnerAccountTypeEnum[keyof typeof OrganisationsGet200ResponseDataInnerAccountTypeEnum];

/**
 * @export
 */
export const OrganisationsGet200ResponseDataInnerStatusEnum = {
    Active: 'ACTIVE',
    Archived: 'ARCHIVED'
} as const;
export type OrganisationsGet200ResponseDataInnerStatusEnum = typeof OrganisationsGet200ResponseDataInnerStatusEnum[keyof typeof OrganisationsGet200ResponseDataInnerStatusEnum];


/**
 * Check if a given object implements the OrganisationsGet200ResponseDataInner interface.
 */
export function instanceOfOrganisationsGet200ResponseDataInner(value: object): value is OrganisationsGet200ResponseDataInner {
    if (!('unprocessedFeedbackCount' in value) || value['unprocessedFeedbackCount'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('billingCycleStartDate' in value) || value['billingCycleStartDate'] === undefined) return false;
    if (!('billingCycleFlexCreditAllowance' in value) || value['billingCycleFlexCreditAllowance'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrganisationsGet200ResponseDataInnerFromJSON(json: any): OrganisationsGet200ResponseDataInner {
    return OrganisationsGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function OrganisationsGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsGet200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'unprocessedFeedbackCount': json['unprocessedFeedbackCount'],
        'id': json['id'],
        'name': json['name'],
        'stripeCustomerId': json['stripeCustomerId'] == null ? undefined : json['stripeCustomerId'],
        'homepageUrl': json['homepageUrl'] == null ? undefined : json['homepageUrl'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'createdAt': json['createdAt'],
        'accountType': json['accountType'],
        'billingCycleStartDate': json['billingCycleStartDate'],
        'billingCycleFlexCreditAllowance': json['billingCycleFlexCreditAllowance'],
        'updatedAt': json['updatedAt'],
        'status': json['status'],
    };
}

export function OrganisationsGet200ResponseDataInnerToJSON(json: any): OrganisationsGet200ResponseDataInner {
    return OrganisationsGet200ResponseDataInnerToJSONTyped(json, false);
}

export function OrganisationsGet200ResponseDataInnerToJSONTyped(value?: OrganisationsGet200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unprocessedFeedbackCount': value['unprocessedFeedbackCount'],
        'id': value['id'],
        'name': value['name'],
        'stripeCustomerId': value['stripeCustomerId'],
        'homepageUrl': value['homepageUrl'],
        'logoUrl': value['logoUrl'],
        'createdAt': value['createdAt'],
        'accountType': value['accountType'],
        'billingCycleStartDate': value['billingCycleStartDate'],
        'billingCycleFlexCreditAllowance': value['billingCycleFlexCreditAllowance'],
        'updatedAt': value['updatedAt'],
        'status': value['status'],
    };
}

