/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Opportunity data
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    read: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    status: OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    solutionsGeneratingState: OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataSolutionsGeneratingStateEnum;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    createdBy: OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataCreatedByEnum;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    hideContent: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData
     */
    updatedAt: string;
}


/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataStatusEnum = {
    New: 'New',
    Solved: 'Solved',
    Planned: 'Planned',
    InProgress: 'InProgress'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataStatusEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataStatusEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataStatusEnum];

/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataSolutionsGeneratingStateEnum = {
    Generating: 'generating',
    Generated: 'generated',
    Initial: 'initial',
    Error: 'error'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataSolutionsGeneratingStateEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataSolutionsGeneratingStateEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataSolutionsGeneratingStateEnum];

/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataCreatedByEnum = {
    User: 'user',
    Generated: 'generated'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataCreatedByEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataCreatedByEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataCreatedByEnum];


/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('read' in value) || value['read'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('solutionsGeneratingState' in value) || value['solutionsGeneratingState'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('hideContent' in value) || value['hideContent'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'read': json['read'],
        'status': json['status'],
        'title': json['title'],
        'description': json['description'],
        'solutionsGeneratingState': json['solutionsGeneratingState'],
        'createdBy': json['createdBy'],
        'hideContent': json['hideContent'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseDataToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesPost200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'read': value['read'],
        'status': value['status'],
        'title': value['title'],
        'description': value['description'],
        'solutionsGeneratingState': value['solutionsGeneratingState'],
        'createdBy': value['createdBy'],
        'hideContent': value['hideContent'],
        'ownerId': value['ownerId'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

