/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request body for managing opportunity relationships
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest {
  /**
   * Array of solution IDs to associate with the opportunity
   * @type {Array<string>}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest
   */
  solutionIds?: Array<string>;
  /**
   * Array of outcome IDs to associate with the opportunity
   * @type {Array<string>}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest
   */
  outcomeIds?: Array<string>;
  /**
   * Array of feedback IDs to associate with the opportunity
   * @type {Array<string>}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest
   */
  insightIds?: Array<string>;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest(
  value: object,
): value is OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest {
  return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequestFromJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest {
  return OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequestFromJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest {
  if (json == null) {
    return json;
  }
  return {
    solutionIds: json["solutionIds"] == null ? undefined : json["solutionIds"],
    outcomeIds: json["outcomeIds"] == null ? undefined : json["outcomeIds"],
    insightIds: json["insightIds"] == null ? undefined : json["insightIds"],
  };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequestToJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest {
  return OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequestToJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequestToJSONTyped(
  value?: OrganisationsOrgIdWorkspacesWorkspaceIdOpportunitiesOpportunityIdRelationshipsActionPostRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    solutionIds: value["solutionIds"],
    outcomeIds: value["outcomeIds"],
    insightIds: value["insightIds"],
  };
}
