/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf {
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf
     */
    service: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfServiceEnum;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf
     */
    model: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfModelEnum;
}


/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfServiceEnum = {
    Claude: 'claude'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfServiceEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfServiceEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfServiceEnum];

/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfModelEnum = {
    ClaudeSonnet420250514: 'claude-sonnet-4-20250514',
    Claude37Sonnet20250219: 'claude-3-7-sonnet-20250219',
    Claude35Sonnet20240620: 'claude-3-5-sonnet-20240620',
    Claude35Sonnet20241022: 'claude-3-5-sonnet-20241022',
    Claude35Haiku20241022: 'claude-3-5-haiku-20241022'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfModelEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfModelEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfModelEnum];


/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'model': json['model'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'model': value['model'],
    };
}

