/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseData } from './OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseData.js';
import {
    OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseDataFromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseDataFromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseDataToJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseDataToJSONTyped,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseData.js';

/**
 * Response containing a success message
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response {
    /**
     * 
     * @type {OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseData}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response
     */
    data: OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseData;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseDataFromJSON(json['data']),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdKnowledgeKnowledgeIdDelete200ResponseDataToJSON(value['data']),
    };
}

