/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest {
    /**
     * Title of the outcome
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest
     */
    title: string;
    /**
     * Detailed description of the outcome
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest
     */
    description: string;
    /**
     * Priority level of the outcome
     * @type {number}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest
     */
    priority: number;
    /**
     * Trend indicator for the outcome
     * @type {number}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest
     */
    trend: number;
    /**
     * List of analytic events associated with the outcome
     * @type {Array<string>}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest
     */
    analyticEvents: Array<string>;
    /**
     * Whether the outcome content should be hidden
     * @type {boolean}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest
     */
    hideContent: boolean;
    /**
     * ID of the outcome owner
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest
     */
    ownerId?: string;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('trend' in value) || value['trend'] === undefined) return false;
    if (!('analyticEvents' in value) || value['analyticEvents'] === undefined) return false;
    if (!('hideContent' in value) || value['hideContent'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequestFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequestFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'priority': json['priority'],
        'trend': json['trend'],
        'analyticEvents': json['analyticEvents'],
        'hideContent': json['hideContent'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequestToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequestToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequestToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'priority': value['priority'],
        'trend': value['trend'],
        'analyticEvents': value['analyticEvents'],
        'hideContent': value['hideContent'],
        'ownerId': value['ownerId'],
    };
}

