/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Success message data
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData {
    /**
     * Success message
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData
     */
    message: string;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseDataFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseDataFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseDataToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseDataToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseDataToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdInsightsInsightIdDelete200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

