/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseData } from './OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseData.js';
import {
    OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseDataFromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseDataFromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseDataToJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseDataToJSONTyped,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseData.js';

/**
 * Response containing a single topic
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response {
    /**
     * 
     * @type {OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseData}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response
     */
    data: OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseData;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseDataFromJSON(json['data']),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdTopicsPost200ResponseDataToJSON(value['data']),
    };
}

