/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Feedback data
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    type: OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    feedback: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    seen: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    hideContent: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    organisationId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData
     */
    updatedAt: string;
}


/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataTypeEnum = {
    Feedback: 'Feedback',
    Bug: 'Bug',
    FeatureRequest: 'FeatureRequest'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataTypeEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataTypeEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataTypeEnum];


/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('feedback' in value) || value['feedback'] === undefined) return false;
    if (!('seen' in value) || value['seen'] === undefined) return false;
    if (!('hideContent' in value) || value['hideContent'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'source': json['source'],
        'title': json['title'],
        'description': json['description'],
        'feedback': json['feedback'],
        'seen': json['seen'],
        'hideContent': json['hideContent'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'organisationId': json['organisationId'],
        'workspaceId': json['workspaceId'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseDataToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'source': value['source'],
        'title': value['title'],
        'description': value['description'],
        'feedback': value['feedback'],
        'seen': value['seen'],
        'hideContent': value['hideContent'],
        'ownerId': value['ownerId'],
        'organisationId': value['organisationId'],
        'workspaceId': value['workspaceId'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

