/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3 {
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3
     */
    service: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ServiceEnum;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3
     */
    model: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ModelEnum;
}


/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ServiceEnum = {
    Openai: 'openai'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ServiceEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ServiceEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ServiceEnum];

/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ModelEnum = {
    O3Mini20250131: 'o3-mini-2025-01-31',
    Gpt4120250414: 'gpt-4.1-2025-04-14'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ModelEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ModelEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ModelEnum];


/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3 interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3 {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3FromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3 {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3FromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3FromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3 {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'model': json['model'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3 {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'model': value['model'],
    };
}

