/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner {
  /**
   * Unique identifier for the outcome
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  id: string;
  /**
   * Title of the outcome
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  title: string;
  /**
   * Detailed description of the outcome
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  description: string;
  /**
   * Priority level of the outcome
   * @type {number}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  priority: number;
  /**
   * Trend indicator for the outcome
   * @type {number}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  trend: number;
  /**
   * List of analytic events associated with the outcome
   * @type {Array<string>}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  analyticEvents: Array<string>;
  /**
   * Whether the outcome content should be hidden
   * @type {boolean}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  hideContent: boolean;
  /**
   * ID of the outcome owner
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  ownerId?: string;
  /**
   * Creation timestamp
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  createdAt: string;
  /**
   * Last update timestamp
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner
   */
  updatedAt: string;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner(
  value: object,
): value is OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("priority" in value) || value["priority"] === undefined) return false;
  if (!("trend" in value) || value["trend"] === undefined) return false;
  if (!("analyticEvents" in value) || value["analyticEvents"] === undefined)
    return false;
  if (!("hideContent" in value) || value["hideContent"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerFromJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner {
  return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerFromJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    description: json["description"],
    priority: json["priority"],
    trend: json["trend"],
    analyticEvents: json["analyticEvents"],
    hideContent: json["hideContent"],
    ownerId: json["ownerId"] == null ? undefined : json["ownerId"],
    createdAt: json["createdAt"],
    updatedAt: json["updatedAt"],
  };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerToJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner {
  return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerToJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerToJSONTyped(
  value?: OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    title: value["title"],
    description: value["description"],
    priority: value["priority"],
    trend: value["trend"],
    analyticEvents: value["analyticEvents"],
    hideContent: value["hideContent"],
    ownerId: value["ownerId"],
    createdAt: value["createdAt"],
    updatedAt: value["updatedAt"],
  };
}
