/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestOptions } from "./OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestOptions.js";
import {
  OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestOptionsFromJSON,
  OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestOptionsToJSON,
} from "./OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestOptions.js";

/**
 * Request body for text proxy processing
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest {
  /**
   * Text prompt to process
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest
   */
  prompt: string;
  /**
   * AI model to use for processing
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest
   */
  model?: string;
  /**
   *
   * @type {OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestOptions}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest
   */
  options?: OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestOptions;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest(
  value: object,
): value is OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest {
  if (!("prompt" in value) || value["prompt"] === undefined) return false;
  return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestFromJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest {
  return OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestFromJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest {
  if (json == null) {
    return json;
  }
  return {
    prompt: json["prompt"],
    model: json["model"] == null ? undefined : json["model"],
    options:
      json["options"] == null
        ? undefined
        : OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestOptionsFromJSON(
            json["options"],
          ),
  };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestToJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest {
  return OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestToJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestToJSONTyped(
  value?: OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prompt: value["prompt"],
    model: value["model"],
    options:
      OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPostRequestOptionsToJSON(
        value["options"],
      ),
  };
}
