/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { RequirementWithRelationships } from './RequirementWithRelationships.js';
import {
    RequirementWithRelationshipsFromJSON,
    RequirementWithRelationshipsFromJSONTyped,
    RequirementWithRelationshipsToJSON,
    RequirementWithRelationshipsToJSONTyped,
} from './RequirementWithRelationships.js';

/**
 * Response containing a single requirement
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response {
    /**
     * Requirement data
     * @type {RequirementWithRelationships}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response
     */
    data: RequirementWithRelationships;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': RequirementWithRelationshipsFromJSON(json['data']),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': RequirementWithRelationshipsToJSON(value['data']),
    };
}

