/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5 {
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5
     */
    service: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ServiceEnum;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5
     */
    model: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ModelEnum;
}


/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ServiceEnum = {
    Jina: 'JINA'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ServiceEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ServiceEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ServiceEnum];

/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ModelEnum = {
    JinaDeepsearchV1: 'jina-deepsearch-v1'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ModelEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ModelEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ModelEnum];


/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5 interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5 {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5FromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5 {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5FromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5FromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5 {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'model': json['model'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5 {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'model': value['model'],
    };
}

