/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf } from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf.js';
import {
    instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfFromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfFromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfToJSON,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1 } from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1.js';
import {
    instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1FromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1FromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1ToJSON,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2 } from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2.js';
import {
    instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2FromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2FromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2ToJSON,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3 } from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3.js';
import {
    instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3FromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3FromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ToJSON,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4 } from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4.js';
import {
    instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4FromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4FromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4ToJSON,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5 } from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5.js';
import {
    instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5FromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5FromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ToJSON,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5.js';

/**
 * @type OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfig
 * 
 * @export
 */
export type OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfig = OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf | OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1 | OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2 | OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3 | OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4 | OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5;

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfig {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfig {
    if (json == null) {
        return json;
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf(json)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfFromJSONTyped(json, true);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1(json)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2(json)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2FromJSONTyped(json, true);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3(json)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3FromJSONTyped(json, true);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4(json)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4FromJSONTyped(json, true);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5(json)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5FromJSONTyped(json, true);
    }

    return {} as any;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigToJSON(json: any): any {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf(value)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOfToJSON(value as OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1(value)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1ToJSON(value as OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf1);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2(value)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2ToJSON(value as OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf2);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3(value)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3ToJSON(value as OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf3);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4(value)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4ToJSON(value as OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf4);
    }
    if (instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5(value)) {
        return OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5ToJSON(value as OrganisationsOrgIdWorkspacesWorkspaceIdTokenUsagePostRequestModelConfigOneOf5);
    }

    return {};
}

