/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response {
    /**
     * Success message
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response
     */
    message: string;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

