/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseData } from './OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseData.js';
import {
    OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseDataFromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseDataFromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseDataToJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseDataToJSONTyped,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseData.js';

/**
 * Response containing a success message
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response {
    /**
     * 
     * @type {OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseData}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response
     */
    data: OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseData;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseDataFromJSON(json['data']),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdMetricsMetricIdDelete200ResponseDataToJSON(value['data']),
    };
}

