/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner } from './OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner.js';
import {
    OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerFromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerFromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerToJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerToJSONTyped,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner.js';

/**
 * Response containing an array of outcomes
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response {
    /**
     * Array of outcomes
     * @type {Array<OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner>}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response
     */
    data: Array<OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInner>;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerFromJSON)),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet200ResponseDataInnerToJSON)),
    };
}

