/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MockFeedbackResponse } from './MockFeedbackResponse.js';
import {
    MockFeedbackResponseFromJSON,
    MockFeedbackResponseFromJSONTyped,
    MockFeedbackResponseToJSON,
    MockFeedbackResponseToJSONTyped,
} from './MockFeedbackResponse.js';

/**
 * 
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response {
    /**
     * 
     * @type {MockFeedbackResponse}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response
     */
    data: MockFeedbackResponse;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': MockFeedbackResponseFromJSON(json['data']),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdMockFeedbackPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MockFeedbackResponseToJSON(value['data']),
    };
}

