/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Workspace data
 * @export
 * @interface OrganisationsOrgIdWorkspacesGet200ResponseInner
 */
export interface OrganisationsOrgIdWorkspacesGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrganisationsOrgIdWorkspacesGet200ResponseInner
     */
    outcomes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesGet200ResponseInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesGet200ResponseInner
     */
    homepageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesGet200ResponseInner
     */
    logoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesGet200ResponseInner
     */
    missionStatement: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesGet200ResponseInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesGet200ResponseInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesGet200ResponseInner
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesGet200ResponseInner interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesGet200ResponseInner(value: object): value is OrganisationsOrgIdWorkspacesGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('outcomes' in value) || value['outcomes'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('missionStatement' in value) || value['missionStatement'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesGet200ResponseInnerFromJSON(json: any): OrganisationsOrgIdWorkspacesGet200ResponseInner {
    return OrganisationsOrgIdWorkspacesGet200ResponseInnerFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'outcomes': json['outcomes'],
        'name': json['name'],
        'homepageUrl': json['homepageUrl'] == null ? undefined : json['homepageUrl'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'missionStatement': json['missionStatement'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function OrganisationsOrgIdWorkspacesGet200ResponseInnerToJSON(json: any): OrganisationsOrgIdWorkspacesGet200ResponseInner {
    return OrganisationsOrgIdWorkspacesGet200ResponseInnerToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesGet200ResponseInnerToJSONTyped(value?: OrganisationsOrgIdWorkspacesGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'outcomes': value['outcomes'],
        'name': value['name'],
        'homepageUrl': value['homepageUrl'],
        'logoUrl': value['logoUrl'],
        'missionStatement': value['missionStatement'],
        'description': value['description'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

