/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FeedbackWithRelationships } from './FeedbackWithRelationships.js';
import {
    FeedbackWithRelationshipsFromJSON,
    FeedbackWithRelationshipsFromJSONTyped,
    FeedbackWithRelationshipsToJSON,
    FeedbackWithRelationshipsToJSONTyped,
} from './FeedbackWithRelationships.js';

/**
 * Response containing a single feedback item
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response {
    /**
     * Feedback data
     * @type {FeedbackWithRelationships}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response
     */
    data: FeedbackWithRelationships;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': FeedbackWithRelationshipsFromJSON(json['data']),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': FeedbackWithRelationshipsToJSON(value['data']),
    };
}

