/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest {
    /**
     * Query string
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest
     */
    query: string;
    /**
     * List of Pinecone sources to search over
     * @type {Array<string>}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest
     */
    filters: Array<OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestFiltersEnum>;
}


/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestFiltersEnum = {
    KnowledgeBase: 'knowledge-base',
    Insights: 'insights',
    Opportunities: 'opportunities',
    Solutions: 'solutions'
} as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestFiltersEnum = typeof OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestFiltersEnum[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestFiltersEnum];


/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest {
    if (!('query' in value) || value['query'] === undefined) return false;
    if (!('filters' in value) || value['filters'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest {
    return OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'filters': json['filters'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest {
    return OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequestToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdSimilaritySearchPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'filters': value['filters'],
    };
}

