/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for updating an organisation
 * @export
 * @interface OrganisationsOrgIdPutRequest
 */
export interface OrganisationsOrgIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdPutRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdPutRequest
     */
    stripeCustomerId?: string;
    /**
     * 
     * @type {number}
     * @memberof OrganisationsOrgIdPutRequest
     */
    maxDailyTokens?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganisationsOrgIdPutRequest
     */
    maxEntities?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganisationsOrgIdPutRequest
     */
    entitiesCreatedCount?: number;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdPutRequest
     */
    homepageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdPutRequest
     */
    logoUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrganisationsOrgIdPutRequest
     */
    outcomeIds?: Array<string>;
}

/**
 * Check if a given object implements the OrganisationsOrgIdPutRequest interface.
 */
export function instanceOfOrganisationsOrgIdPutRequest(value: object): value is OrganisationsOrgIdPutRequest {
    return true;
}

export function OrganisationsOrgIdPutRequestFromJSON(json: any): OrganisationsOrgIdPutRequest {
    return OrganisationsOrgIdPutRequestFromJSONTyped(json, false);
}

export function OrganisationsOrgIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'stripeCustomerId': json['stripeCustomerId'] == null ? undefined : json['stripeCustomerId'],
        'maxDailyTokens': json['maxDailyTokens'] == null ? undefined : json['maxDailyTokens'],
        'maxEntities': json['maxEntities'] == null ? undefined : json['maxEntities'],
        'entitiesCreatedCount': json['entitiesCreatedCount'] == null ? undefined : json['entitiesCreatedCount'],
        'homepageUrl': json['homepageUrl'] == null ? undefined : json['homepageUrl'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'outcomeIds': json['outcomeIds'] == null ? undefined : json['outcomeIds'],
    };
}

export function OrganisationsOrgIdPutRequestToJSON(json: any): OrganisationsOrgIdPutRequest {
    return OrganisationsOrgIdPutRequestToJSONTyped(json, false);
}

export function OrganisationsOrgIdPutRequestToJSONTyped(value?: OrganisationsOrgIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'stripeCustomerId': value['stripeCustomerId'],
        'maxDailyTokens': value['maxDailyTokens'],
        'maxEntities': value['maxEntities'],
        'entitiesCreatedCount': value['entitiesCreatedCount'],
        'homepageUrl': value['homepageUrl'],
        'logoUrl': value['logoUrl'],
        'outcomeIds': value['outcomeIds'],
    };
}

