/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsGet200ResponseInnerRefinementLogInner } from "./OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsGet200ResponseInnerRefinementLogInner.js";
import {
  OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsGet200ResponseInnerRefinementLogInnerFromJSON,
  OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsGet200ResponseInnerRefinementLogInnerToJSON,
} from "./OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsGet200ResponseInnerRefinementLogInner.js";

/**
 * Solution data for an opportunity
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  systemPrompt: string | null;
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  aiProcessingState: OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerAiProcessingStateEnum;
  /**
   *
   * @type {Array<OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsGet200ResponseInnerRefinementLogInner>}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  refinementLog: Array<OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsGet200ResponseInnerRefinementLogInner>;
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  status: OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerStatusEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  pros: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  cons: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  hideContent: boolean;
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  createdBy: OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerCreatedByEnum;
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  ownerId?: string;
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner
   */
  updatedAt: string;
}

/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerAiProcessingStateEnum =
  {
    Initial: "INITIAL",
    Processing: "PROCESSING",
    Finished: "FINISHED",
    Error: "ERROR",
  } as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerAiProcessingStateEnum =
  (typeof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerAiProcessingStateEnum)[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerAiProcessingStateEnum];

/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerStatusEnum =
  {
    New: "New",
    Solved: "Solved",
    Planned: "Planned",
    InProgress: "InProgress",
  } as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerStatusEnum =
  (typeof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerStatusEnum)[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerStatusEnum];

/**
 * @export
 */
export const OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerCreatedByEnum =
  {
    User: "user",
    Generated: "generated",
  } as const;
export type OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerCreatedByEnum =
  (typeof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerCreatedByEnum)[keyof typeof OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerCreatedByEnum];

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner(
  value: object,
): value is OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("systemPrompt" in value) || value["systemPrompt"] === undefined)
    return false;
  if (
    !("aiProcessingState" in value) ||
    value["aiProcessingState"] === undefined
  )
    return false;
  if (!("refinementLog" in value) || value["refinementLog"] === undefined)
    return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("pros" in value) || value["pros"] === undefined) return false;
  if (!("cons" in value) || value["cons"] === undefined) return false;
  if (!("hideContent" in value) || value["hideContent"] === undefined)
    return false;
  if (!("createdBy" in value) || value["createdBy"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerFromJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner {
  return OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerFromJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    systemPrompt: json["systemPrompt"],
    aiProcessingState: json["aiProcessingState"],
    refinementLog: (json["refinementLog"] as Array<any>).map(
      OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsGet200ResponseInnerRefinementLogInnerFromJSON,
    ),
    title: json["title"],
    description: json["description"],
    status: json["status"],
    pros: json["pros"],
    cons: json["cons"],
    hideContent: json["hideContent"],
    createdBy: json["createdBy"],
    ownerId: json["ownerId"] == null ? undefined : json["ownerId"],
    createdAt: json["createdAt"],
    updatedAt: json["updatedAt"],
  };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerToJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner {
  return OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerToJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInnerToJSONTyped(
  value?: OrganisationsOrgIdWorkspacesWorkspaceIdSolutionsGet200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    systemPrompt: value["systemPrompt"],
    aiProcessingState: value["aiProcessingState"],
    refinementLog: (value["refinementLog"] as Array<any>).map(
      OrganisationsOrgIdWorkspacesWorkspaceIdRequirementsGet200ResponseInnerRefinementLogInnerToJSON,
    ),
    title: value["title"],
    description: value["description"],
    status: value["status"],
    pros: value["pros"],
    cons: value["cons"],
    hideContent: value["hideContent"],
    createdBy: value["createdBy"],
    ownerId: value["ownerId"],
    createdAt: value["createdAt"],
    updatedAt: value["updatedAt"],
  };
}
