/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError {
  /**
   * Error code identifier
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError
   */
  code: string;
  /**
   * Human-readable error description
   * @type {string}
   * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError
   */
  description: string;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError(
  value: object,
): value is OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseErrorFromJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError {
  return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseErrorFromJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    description: json["description"],
  };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseErrorToJSON(
  json: any,
): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError {
  return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseErrorToJSONTyped(
    json,
    false,
  );
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseErrorToJSONTyped(
  value?: OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesOutcomeIdGet404ResponseError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    description: value["description"],
  };
}
