/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Success message data
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData {
    /**
     * Success message
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData
     */
    message: string;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseDataFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseDataFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseDataToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseDataToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseDataToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdTopicsTopicIdDelete200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

