/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseData } from './OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseData.js';
import {
    OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseDataFromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseDataFromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseDataToJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseDataToJSONTyped,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseData.js';

/**
 * Response containing a success message
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response {
    /**
     * 
     * @type {OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseData}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response
     */
    data: OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseData;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseDataFromJSON(json['data']),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdFeedbackFeedbackIdDelete200ResponseDataToJSON(value['data']),
    };
}

