/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError {
    /**
     * Error code identifier
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError
     */
    code: string;
    /**
     * Human-readable error description
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError
     */
    description: string;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseErrorFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseErrorFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseErrorToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseErrorToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseErrorToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesGet401ResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

