/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseData } from './OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseData.js';
import {
    OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseDataFromJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseDataFromJSONTyped,
    OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseDataToJSON,
    OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseDataToJSONTyped,
} from './OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseData.js';

/**
 * Response containing a single outcome
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response {
    /**
     * 
     * @type {OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseData}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response
     */
    data: OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseData;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseDataFromJSON(json['data']),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': OrganisationsOrgIdWorkspacesWorkspaceIdOutcomesPost200ResponseDataToJSON(value['data']),
    };
}

