/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Metric } from './Metric.js';
import {
    MetricFromJSON,
    MetricFromJSONTyped,
    MetricToJSON,
    MetricToJSONTyped,
} from './Metric.js';

/**
 * Response containing a single  metric
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response {
    /**
     * 
     * @type {Metric}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response
     */
    data: Metric;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200ResponseFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200ResponseFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': MetricFromJSON(json['data']),
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200ResponseToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response {
    return OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200ResponseToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200ResponseToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdMetricsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MetricToJSON(value['data']),
    };
}

