/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for updating a workspace
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest
     */
    missionStatement?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest
     */
    homepageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest
     */
    logoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest
     */
    outcomes?: Array<string>;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdPutRequest(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest {
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdPutRequestFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest {
    return OrganisationsOrgIdWorkspacesWorkspaceIdPutRequestFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'missionStatement': json['missionStatement'] == null ? undefined : json['missionStatement'],
        'homepageUrl': json['homepageUrl'] == null ? undefined : json['homepageUrl'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'description': json['description'] == null ? undefined : json['description'],
        'outcomes': json['outcomes'] == null ? undefined : json['outcomes'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdPutRequestToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest {
    return OrganisationsOrgIdWorkspacesWorkspaceIdPutRequestToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdPutRequestToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'missionStatement': value['missionStatement'],
        'homepageUrl': value['homepageUrl'],
        'logoUrl': value['logoUrl'],
        'description': value['description'],
        'outcomes': value['outcomes'],
    };
}

