/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData
 */
export interface OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData {
    /**
     * Processed text result
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData
     */
    result: string;
    /**
     * AI model used for processing
     * @type {string}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData
     */
    model: string;
    /**
     * Time taken to process the request in milliseconds
     * @type {number}
     * @memberof OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData
     */
    processingTime: number;
}

/**
 * Check if a given object implements the OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData interface.
 */
export function instanceOfOrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData(value: object): value is OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('processingTime' in value) || value['processingTime'] === undefined) return false;
    return true;
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseDataFromJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseDataFromJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
        'model': json['model'],
        'processingTime': json['processingTime'],
    };
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseDataToJSON(json: any): OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData {
    return OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseDataToJSONTyped(json, false);
}

export function OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseDataToJSONTyped(value?: OrganisationsOrgIdWorkspacesWorkspaceIdTestProxyPost200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'model': value['model'],
        'processingTime': value['processingTime'],
    };
}

