/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request body for managing outcome relationships
 * @export
 * @interface OutcomeRelationshipsPayload
 */
export interface OutcomeRelationshipsPayload {
    /**
     * Array of opportunity IDs to associate with the outcome
     * @type {Array<string>}
     * @memberof OutcomeRelationshipsPayload
     */
    opportunityIds?: Array<string>;
    /**
     * Array of solution IDs to associate with the outcome
     * @type {Array<string>}
     * @memberof OutcomeRelationshipsPayload
     */
    solutionIds?: Array<string>;
    /**
     * Array of feedback IDs to associate with the outcome
     * @type {Array<string>}
     * @memberof OutcomeRelationshipsPayload
     */
    feedbackIds?: Array<string>;
}

/**
 * Check if a given object implements the OutcomeRelationshipsPayload interface.
 */
export function instanceOfOutcomeRelationshipsPayload(value: object): value is OutcomeRelationshipsPayload {
    return true;
}

export function OutcomeRelationshipsPayloadFromJSON(json: any): OutcomeRelationshipsPayload {
    return OutcomeRelationshipsPayloadFromJSONTyped(json, false);
}

export function OutcomeRelationshipsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutcomeRelationshipsPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'opportunityIds': json['opportunityIds'] == null ? undefined : json['opportunityIds'],
        'solutionIds': json['solutionIds'] == null ? undefined : json['solutionIds'],
        'feedbackIds': json['feedbackIds'] == null ? undefined : json['feedbackIds'],
    };
}

export function OutcomeRelationshipsPayloadToJSON(json: any): OutcomeRelationshipsPayload {
    return OutcomeRelationshipsPayloadToJSONTyped(json, false);
}

export function OutcomeRelationshipsPayloadToJSONTyped(value?: OutcomeRelationshipsPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opportunityIds': value['opportunityIds'],
        'solutionIds': value['solutionIds'],
        'feedbackIds': value['feedbackIds'],
    };
}

