/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RelationshipAction = {
  Add: "add",
  Remove: "remove",
} as const;
export type RelationshipAction =
  (typeof RelationshipAction)[keyof typeof RelationshipAction];

export function instanceOfRelationshipAction(value: any): boolean {
  for (const key in RelationshipAction) {
    if (Object.prototype.hasOwnProperty.call(RelationshipAction, key)) {
      if (
        RelationshipAction[key as keyof typeof RelationshipAction] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function RelationshipActionFromJSON(json: any): RelationshipAction {
  return RelationshipActionFromJSONTyped(json, false);
}

export function RelationshipActionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RelationshipAction {
  return json as RelationshipAction;
}

export function RelationshipActionToJSON(
  value?: RelationshipAction | null,
): any {
  return value as any;
}

export function RelationshipActionToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): RelationshipAction {
  return value as RelationshipAction;
}
