/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SingleKnowledgeResponseData
 */
export interface SingleKnowledgeResponseData {
    /**
     * Knowledge content - the full content of the knowledge, this will only be available post processing
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    content?: string;
    /**
     * Knowledge ID
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    id: string;
    /**
     * Knowledge state
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    state: SingleKnowledgeResponseDataStateEnum;
    /**
     * Knowledge title
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    title: string;
    /**
     * Knowledge description - a short summary of the knowledge
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    description: string;
    /**
     * Knowledge creation timestamp
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    createdAt: string;
    /**
     * Knowledge update timestamp
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    updatedAt: string;
    /**
     * Type of knowledge
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    source: SingleKnowledgeResponseDataSourceEnum;
    /**
     * URL of the PDF file of the knowledge (mutually exclusive with url)
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    pdfFileUrl?: string;
    /**
     * URL of the TXT file of the knowledge (mutually exclusive with url)
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    txtFileUrl?: string;
    /**
     * URL of the knowledge source (mutually exclusive with filePath)
     * @type {string}
     * @memberof SingleKnowledgeResponseData
     */
    url?: string;
}


/**
 * @export
 */
export const SingleKnowledgeResponseDataStateEnum = {
    Initial: 'initial',
    Processing: 'processing',
    Completed: 'completed',
    Error: 'error'
} as const;
export type SingleKnowledgeResponseDataStateEnum = typeof SingleKnowledgeResponseDataStateEnum[keyof typeof SingleKnowledgeResponseDataStateEnum];

/**
 * @export
 */
export const SingleKnowledgeResponseDataSourceEnum = {
    Text: 'text',
    Url: 'url',
    Pdf: 'pdf'
} as const;
export type SingleKnowledgeResponseDataSourceEnum = typeof SingleKnowledgeResponseDataSourceEnum[keyof typeof SingleKnowledgeResponseDataSourceEnum];


/**
 * Check if a given object implements the SingleKnowledgeResponseData interface.
 */
export function instanceOfSingleKnowledgeResponseData(value: object): value is SingleKnowledgeResponseData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function SingleKnowledgeResponseDataFromJSON(json: any): SingleKnowledgeResponseData {
    return SingleKnowledgeResponseDataFromJSONTyped(json, false);
}

export function SingleKnowledgeResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleKnowledgeResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'id': json['id'],
        'state': json['state'],
        'title': json['title'],
        'description': json['description'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'source': json['source'],
        'pdfFileUrl': json['pdfFileUrl'] == null ? undefined : json['pdfFileUrl'],
        'txtFileUrl': json['txtFileUrl'] == null ? undefined : json['txtFileUrl'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function SingleKnowledgeResponseDataToJSON(json: any): SingleKnowledgeResponseData {
    return SingleKnowledgeResponseDataToJSONTyped(json, false);
}

export function SingleKnowledgeResponseDataToJSONTyped(value?: SingleKnowledgeResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'id': value['id'],
        'state': value['state'],
        'title': value['title'],
        'description': value['description'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'source': value['source'],
        'pdfFileUrl': value['pdfFileUrl'],
        'txtFileUrl': value['txtFileUrl'],
        'url': value['url'],
    };
}

