/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request body for managing solution relationships
 * @export
 * @interface SolutionRelationshipsPayload
 */
export interface SolutionRelationshipsPayload {
    /**
     * Array of opportunity IDs to associate with the solution
     * @type {Array<string>}
     * @memberof SolutionRelationshipsPayload
     */
    opportunityIds?: Array<string>;
    /**
     * Array of requirement IDs to associate with the solution
     * @type {Array<string>}
     * @memberof SolutionRelationshipsPayload
     */
    requirementIds?: Array<string>;
}

/**
 * Check if a given object implements the SolutionRelationshipsPayload interface.
 */
export function instanceOfSolutionRelationshipsPayload(value: object): value is SolutionRelationshipsPayload {
    return true;
}

export function SolutionRelationshipsPayloadFromJSON(json: any): SolutionRelationshipsPayload {
    return SolutionRelationshipsPayloadFromJSONTyped(json, false);
}

export function SolutionRelationshipsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolutionRelationshipsPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'opportunityIds': json['opportunityIds'] == null ? undefined : json['opportunityIds'],
        'requirementIds': json['requirementIds'] == null ? undefined : json['requirementIds'],
    };
}

export function SolutionRelationshipsPayloadToJSON(json: any): SolutionRelationshipsPayload {
    return SolutionRelationshipsPayloadToJSONTyped(json, false);
}

export function SolutionRelationshipsPayloadToJSONTyped(value?: SolutionRelationshipsPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opportunityIds': value['opportunityIds'],
        'requirementIds': value['requirementIds'],
    };
}

