/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request schema for updating an opportunity
 * @export
 * @interface UpdateOpportunityPayload
 */
export interface UpdateOpportunityPayload {
    /**
     * 
     * @type {string}
     * @memberof UpdateOpportunityPayload
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOpportunityPayload
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateOpportunityPayload
     */
    status?: UpdateOpportunityPayloadStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateOpportunityPayload
     */
    solutionsGeneratingState?: UpdateOpportunityPayloadSolutionsGeneratingStateEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateOpportunityPayload
     */
    hideContent?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateOpportunityPayload
     */
    ownerId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateOpportunityPayload
     */
    read?: boolean;
}


/**
 * @export
 */
export const UpdateOpportunityPayloadStatusEnum = {
    New: 'New',
    Solved: 'Solved',
    Planned: 'Planned',
    InProgress: 'InProgress'
} as const;
export type UpdateOpportunityPayloadStatusEnum = typeof UpdateOpportunityPayloadStatusEnum[keyof typeof UpdateOpportunityPayloadStatusEnum];

/**
 * @export
 */
export const UpdateOpportunityPayloadSolutionsGeneratingStateEnum = {
    Generating: 'generating',
    Generated: 'generated',
    Initial: 'initial',
    Error: 'error'
} as const;
export type UpdateOpportunityPayloadSolutionsGeneratingStateEnum = typeof UpdateOpportunityPayloadSolutionsGeneratingStateEnum[keyof typeof UpdateOpportunityPayloadSolutionsGeneratingStateEnum];


/**
 * Check if a given object implements the UpdateOpportunityPayload interface.
 */
export function instanceOfUpdateOpportunityPayload(value: object): value is UpdateOpportunityPayload {
    return true;
}

export function UpdateOpportunityPayloadFromJSON(json: any): UpdateOpportunityPayload {
    return UpdateOpportunityPayloadFromJSONTyped(json, false);
}

export function UpdateOpportunityPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOpportunityPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'solutionsGeneratingState': json['solutionsGeneratingState'] == null ? undefined : json['solutionsGeneratingState'],
        'hideContent': json['hideContent'] == null ? undefined : json['hideContent'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'read': json['read'] == null ? undefined : json['read'],
    };
}

export function UpdateOpportunityPayloadToJSON(json: any): UpdateOpportunityPayload {
    return UpdateOpportunityPayloadToJSONTyped(json, false);
}

export function UpdateOpportunityPayloadToJSONTyped(value?: UpdateOpportunityPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
        'solutionsGeneratingState': value['solutionsGeneratingState'],
        'hideContent': value['hideContent'],
        'ownerId': value['ownerId'],
        'read': value['read'],
    };
}

