/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FeedbackResponse } from './FeedbackResponse.js';
import {
    FeedbackResponseFromJSON,
    FeedbackResponseFromJSONTyped,
    FeedbackResponseToJSON,
    FeedbackResponseToJSONTyped,
} from './FeedbackResponse.js';

/**
 * 
 * @export
 * @interface V1DataIngressPost201Response
 */
export interface V1DataIngressPost201Response {
    /**
     * 
     * @type {FeedbackResponse}
     * @memberof V1DataIngressPost201Response
     */
    data: FeedbackResponse;
}

/**
 * Check if a given object implements the V1DataIngressPost201Response interface.
 */
export function instanceOfV1DataIngressPost201Response(value: object): value is V1DataIngressPost201Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function V1DataIngressPost201ResponseFromJSON(json: any): V1DataIngressPost201Response {
    return V1DataIngressPost201ResponseFromJSONTyped(json, false);
}

export function V1DataIngressPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DataIngressPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': FeedbackResponseFromJSON(json['data']),
    };
}

export function V1DataIngressPost201ResponseToJSON(json: any): V1DataIngressPost201Response {
    return V1DataIngressPost201ResponseToJSONTyped(json, false);
}

export function V1DataIngressPost201ResponseToJSONTyped(value?: V1DataIngressPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': FeedbackResponseToJSON(value['data']),
    };
}

