/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * API for managing Squad resources
 *
 * The version of the OpenAPI document: 0.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Response data for processed feedback
 * @export
 * @interface V1DataIngressPost201ResponseData
 */
export interface V1DataIngressPost201ResponseData {
    /**
     * The feedback content
     * @type {string}
     * @memberof V1DataIngressPost201ResponseData
     */
    feedback: string;
    /**
     * The source of the feedback
     * @type {string}
     * @memberof V1DataIngressPost201ResponseData
     */
    source: V1DataIngressPost201ResponseDataSourceEnum;
    /**
     * ID of the workspace
     * @type {string}
     * @memberof V1DataIngressPost201ResponseData
     */
    workspaceId: string;
    /**
     * ID of the organization
     * @type {string}
     * @memberof V1DataIngressPost201ResponseData
     */
    organisationId: string;
}


/**
 * @export
 */
export const V1DataIngressPost201ResponseDataSourceEnum = {
    Typeform: 'TYPEFORM',
    Slack: 'SLACK',
    Unknown: 'UNKNOWN',
    Manual: 'MANUAL'
} as const;
export type V1DataIngressPost201ResponseDataSourceEnum = typeof V1DataIngressPost201ResponseDataSourceEnum[keyof typeof V1DataIngressPost201ResponseDataSourceEnum];


/**
 * Check if a given object implements the V1DataIngressPost201ResponseData interface.
 */
export function instanceOfV1DataIngressPost201ResponseData(value: object): value is V1DataIngressPost201ResponseData {
    if (!('feedback' in value) || value['feedback'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    return true;
}

export function V1DataIngressPost201ResponseDataFromJSON(json: any): V1DataIngressPost201ResponseData {
    return V1DataIngressPost201ResponseDataFromJSONTyped(json, false);
}

export function V1DataIngressPost201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DataIngressPost201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'feedback': json['feedback'],
        'source': json['source'],
        'workspaceId': json['workspaceId'],
        'organisationId': json['organisationId'],
    };
}

export function V1DataIngressPost201ResponseDataToJSON(json: any): V1DataIngressPost201ResponseData {
    return V1DataIngressPost201ResponseDataToJSONTyped(json, false);
}

export function V1DataIngressPost201ResponseDataToJSONTyped(value?: V1DataIngressPost201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feedback': value['feedback'],
        'source': value['source'],
        'workspaceId': value['workspaceId'],
        'organisationId': value['organisationId'],
    };
}

