# .github/workflows/release.yml
name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on semantic version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create the release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your project's required Node.js version

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a specific Bun version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/* # Upload all files from the bin directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
